"""
NLM Admin API — FastAPI backend
When extension sends cookies:
  1. Writes cookies.txt (Netscape format)
  2. Writes cookie_env.txt (plain cookie string for NOTEBOOKLM_COOKIES)
  3. Kills old notebooklm-mcp process and starts new one with NOTEBOOKLM_COOKIES set
Operator clicks once — everything else is automatic.
"""

import io
import json
import os
import subprocess
import time
import zipfile
from datetime import datetime
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles

app = FastAPI(title="NLM Auth Manager", docs_url=None, redoc_url=None)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

ADMIN_SECRET  = os.getenv("ADMIN_SECRET", "c8club-nlm-admin")
COOKIES_DIR   = Path("/root/.notebooklm-mcp-cli")
COOKIES_FILE  = COOKIES_DIR / "cookies.txt"
COOKIE_ENV    = COOKIES_DIR / "cookie_env.txt"   # read by start.sh on boot
STATIC_DIR    = Path(__file__).parent / "static"
EXTENSION_DIR = STATIC_DIR / "extension"

_auth = {"status": "idle", "account": None, "cookie_count": 0, "source": None}


def _verify(secret: str):
    if secret != ADMIN_SECRET:
        raise HTTPException(status_code=401, detail="Acesso nao autorizado")


def _write_nlm_profile(cookie_dict: dict) -> tuple[bool, str]:
    """
    Writes cookies directly to the nlm profile JSON files:
      ~/.notebooklm-mcp-cli/profiles/default/cookies.json  (dict name->value)
      ~/.notebooklm-mcp-cli/profiles/default/metadata.json
    This bypasses 'nlm login' entirely — no subprocess, no browser, no Netscape.
    The nlm MCP server reads this profile on every request.
    """
    try:
        from notebooklm_tools.utils.config import get_profile_dir  # type: ignore
        profile_dir = get_profile_dir("default")
    except Exception:
        # Fallback path if import fails
        profile_dir = COOKIES_DIR / "profiles" / "default"

    profile_dir.mkdir(parents=True, exist_ok=True)
    profile_dir.chmod(0o700)

    cookies_file = profile_dir / "cookies.json"
    metadata_file = profile_dir / "metadata.json"

    cookies_file.write_text(
        json.dumps(cookie_dict, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    cookies_file.chmod(0o600)

    metadata_file.write_text(
        json.dumps({
            "last_validated": datetime.now().isoformat(),
            "email": None,
            "csrf_token": None,
            "session_id": None,
        }, indent=2),
        encoding="utf-8"
    )
    metadata_file.chmod(0o600)

    return True, str(cookies_file)


# ── Status ─────────────────────────────────────────────────────────────────────

@app.get("/api/status")
async def get_status():
    if COOKIES_FILE.exists() and COOKIES_FILE.stat().st_size > 50:
        _auth["status"] = "authenticated"
    return {
        "status": _auth["status"],
        "account": _auth["account"],
        "cookie_count": _auth.get("cookie_count", 0),
        "source": _auth.get("source"),
    }


# ── Auth: receives cookies, writes files, restarts nlm with auth ───────────────

@app.post("/api/auth-bookmarklet")
async def auth_bookmarklet(body: dict):
    """
    1. Receives cookies from Chrome Extension (includes HttpOnly)
    2. Writes Netscape cookies.txt
    3. Writes cookie_env.txt (for persistence across container restarts)
    4. Restarts notebooklm-mcp with NOTEBOOKLM_COOKIES env var — auth is live immediately
    """
    _verify(body.get("secret", ""))

    source        = body.get("source", "bookmarklet")
    cookie_objects = body.get("cookies", [])
    cookie_string  = body.get("cookies_string", "")

    if isinstance(cookie_objects, str):
        cookie_string  = cookie_objects
        cookie_objects = []

    if not cookie_objects and not cookie_string:
        raise HTTPException(status_code=400, detail="Nenhum cookie recebido")

    COOKIES_DIR.mkdir(parents=True, exist_ok=True)

    try:
        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by NLM Admin Manager - C8Club",
        ]
        expiry_far  = int(time.time()) + (86400 * 365)
        count       = 0
        cookie_pairs = []

        if cookie_objects and isinstance(cookie_objects, list):
            for c in cookie_objects:
                if not isinstance(c, dict) or not c.get("name"):
                    continue
                name   = c.get("name", "")
                value  = c.get("value", "")
                domain = c.get("domain", ".google.com")
                path   = c.get("path", "/")
                secure = "TRUE" if c.get("secure", False) else "FALSE"
                expiry = int(c.get("expirationDate", expiry_far))
                if not domain.startswith("."):
                    domain = "." + domain
                lines.append(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
                cookie_pairs.append(f"{name}={value}")
                count += 1

        elif cookie_string:
            for part in cookie_string.split(";"):
                part = part.strip()
                if "=" in part:
                    key, _, val = part.partition("=")
                    key, val = key.strip(), val.strip()
                    lines.append(f".google.com\tTRUE\t/\tFALSE\t{expiry_far}\t{key}\t{val}")
                    lines.append(f".notebooklm.google.com\tTRUE\t/\tFALSE\t{expiry_far}\t{key}\t{val}")
                    cookie_pairs.append(f"{key}={val}")
                    count += 1

        cookie_header = "; ".join(cookie_pairs)
        cookie_dict   = dict(pair.split("=", 1) for pair in cookie_pairs if "=" in pair)

        # Write Netscape cookies.txt (legacy compat)
        COOKIES_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

        # Write cookie_env.txt (read by start.sh on next boot)
        COOKIE_ENV.write_text(cookie_header, encoding="utf-8")

        # Write directly to nlm profile JSON (what nlm actually reads)
        ok, info = _write_nlm_profile(cookie_dict)

        _auth["status"]       = "authenticated"
        _auth["cookie_count"] = count
        _auth["source"]       = source

        msg = f"OK {count} cookies via {'extensao Chrome' if source == 'chrome_extension' else 'bookmarklet'}!"
        if ok:
            msg += f" NLM autenticado: {info}"
        else:
            msg += f" Aviso nlm login: {info}"

        return {"message": msg, "count": count, "source": source, "nlm_ok": ok}

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Erro: {str(e)}")


# ── Extension ZIP ──────────────────────────────────────────────────────────────

@app.get("/api/extension.zip")
async def download_extension():
    if not EXTENSION_DIR.exists():
        raise HTTPException(status_code=404, detail="Extension not found")
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in EXTENSION_DIR.rglob("*"):
            if f.is_file():
                zf.write(f, f.relative_to(EXTENSION_DIR))
    buf.seek(0)
    return StreamingResponse(
        buf, media_type="application/zip",
        headers={"Content-Disposition": "attachment; filename=nlm-c8club-auth-extension.zip"},
    )


@app.get("/health")
async def health():
    return {"status": "ok"}


STATIC_DIR.mkdir(exist_ok=True)
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


@app.get("/", response_class=HTMLResponse)
async def root():
    index = STATIC_DIR / "index.html"
    if index.exists():
        return FileResponse(str(index))
    return HTMLResponse("<h1>NLM Admin</h1>")
