"""
NLM Admin API — FastAPI backend
Bookmarklet-based auth: recebe cookies do browser do operador via fetch(),
salva em /root/.notebooklm-mcp-cli/cookies.txt para o MCP server usar.
Zero VNC/Chromium inside Docker.
"""

import os
import subprocess
import time
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles

app = FastAPI(title="NLM Auth Manager", docs_url=None, redoc_url=None)

ADMIN_SECRET = os.getenv("ADMIN_SECRET", "c8club-nlm-admin")
COOKIES_DIR = Path("/root/.notebooklm-mcp-cli")
COOKIES_FILE = COOKIES_DIR / "cookies.txt"

# Auth state
_auth = {"status": "idle", "account": None}


def _verify(secret: str):
    if secret != ADMIN_SECRET:
        raise HTTPException(status_code=401, detail="Acesso não autorizado")


# ── Bookmarklet Auth Endpoint ──────────────────────────────────────────────────

@app.post("/api/auth-bookmarklet")
async def auth_bookmarklet(body: dict):
    """
    Recebe cookies enviados pelo bookmarklet do browser do operador.
    O operador está logado em notebooklm.google.com e o bookmarklet
    envia document.cookie via fetch() para cá.
    """
    _verify(body.get("secret", ""))

    cookies_str = body.get("cookies", "").strip()
    url = body.get("url", "")

    if not cookies_str:
        raise HTTPException(status_code=400, detail="Nenhum cookie recebido")

    if "notebooklm" not in url and "google" not in url:
        raise HTTPException(
            status_code=400,
            detail="Abra o bookmarklet estando em notebooklm.google.com"
        )

    # Save cookies in Netscape format for nlm to use
    COOKIES_DIR.mkdir(parents=True, exist_ok=True)

    try:
        # Parse "key=value; key2=value2" cookie string into Netscape format
        lines = ["# Netscape HTTP Cookie File", "# Generated by NLM Admin Manager"]
        for part in cookies_str.split(";"):
            part = part.strip()
            if "=" in part:
                key, _, value = part.partition("=")
                key = key.strip()
                value = value.strip()
                # Netscape cookie format: domain flag path secure expiry name value
                lines.append(f".google.com\tTRUE\t/\tFALSE\t{int(time.time()) + 86400 * 365}\t{key}\t{value}")
                lines.append(f".notebooklm.google.com\tTRUE\t/\tFALSE\t{int(time.time()) + 86400 * 365}\t{key}\t{value}")

        COOKIES_FILE.write_text("\n".join(lines) + "\n")
        _auth["status"] = "authenticated"

        # Try to extract account from cookies
        for part in cookies_str.split(";"):
            if "GMAIL_AT" in part or "ACCOUNT_CHOOSER" in part:
                _auth["account"] = "conta@c8club.com.br"
                break

        return {"message": "✅ Autenticação salva com sucesso! O sistema NLM está ativo."}

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Erro ao salvar cookies: {str(e)}")


# ── Status Endpoint ────────────────────────────────────────────────────────────

@app.get("/api/status")
async def get_status():
    # Check file-based auth state
    if COOKIES_FILE.exists() and COOKIES_FILE.stat().st_size > 100:
        _auth["status"] = "authenticated"
    else:
        # Also try nlm --check if available
        try:
            r = subprocess.run(
                ["nlm", "login", "--check"],
                capture_output=True, text=True, timeout=5,
            )
            if r.returncode == 0 and "authenticated" in (r.stdout + r.stderr).lower():
                _auth["status"] = "authenticated"
        except Exception:
            pass

    return {"status": _auth["status"], "account": _auth["account"]}


@app.get("/health")
async def health():
    return {"status": "ok", "service": "nlm-admin"}


# ── Static Files ───────────────────────────────────────────────────────────────
static_dir = Path(__file__).parent / "static"
static_dir.mkdir(exist_ok=True)
app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")


@app.get("/", response_class=HTMLResponse)
async def root():
    index = static_dir / "index.html"
    if index.exists():
        return FileResponse(str(index))
    return HTMLResponse("<h1>NLM Admin</h1>")
